version: 2
terraform_runner:
  workspaces:
    terraform/**:
      watchlist:
        - out/**
      build:
        included_files:
          - out/**
      plan:
        environment_variables:
          - name: ETHERSCAN_API_KEY
            type: config_service_secret
            scope: infra/provisioner-worker-tfstatic-unprivileged-smart-contracts/flywheel-protocol
            parameter: etherscan_api_key_read
      apply:
        environment_variables:
          - name: ETHERSCAN_API_KEY
            type: config_service_secret
            scope: infra/provisioner-worker-tfstatic-privileged-smart-contracts/flywheel-protocol
            parameter: etherscan_api_key_write
# Create two config service scopes, named exactly as defined in the `.infraprovisioner.yml` file, and add the `etherscan_api_key_read` and `etherscan_api_key_write` parameters. Note that `etherscan_api_key_read` belongs to the unprivileged scope, and `etherscan_api_key_write` belongs to the privileged scope. Also add in the Allowed Principals, similar to these examples: Unprivileged scope [example](https://config.cbhq.net/core-infraprovisioner-prod-use1/infra/provisioner-worker-tfstatic-unprivileged-smart-contracts/emerging-talent-riddle-bounty), Privileged scope [example](https://config.cbhq.net/core-infraprovisioner-prod-use1/infra/provisioner-worker-tfstatic-privileged-smart-contracts/emerging-talent-riddle-bounty)
# If you need an etherscan api key, you can create an [etherscan](https://docs.etherscan.io/getting-started/viewing-api-usage-statistics) account to get an api key. We dont use a corporate api key for now since the request rate for a normal developer key is sufficient.
# one more
